[package]
name = "parser"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]

[lib]
crate-type = ["lib", "cdylib"]

[features]
wasm = ["wasm-bindgen", "wee_alloc"]
default = []

[dependencies]
nom = { git = "https://github.com/Geal/nom", branch = "master", default-features = false, features = [ "alloc" ] }
serde_json = "^1.0"
wasm-bindgen = { version = "^0.2", optional = true }
wee_alloc = { version = "^0.2", optional = true }