[package]
name = "parser"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
nom = {"git" = "https://github.com/Geal/nom", "branch" = "master"}
wasm-bindgen = "^0.2"
wee_alloc = "^0.2"
regex = "^0.2"
lazy_static = "^1.0"
serde_json = "^1.0"