[package]
name = "parser"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
debug = false
lto = true

[features]
wasm = ["wasm-bindgen", "wee_alloc"]
default = []

[dependencies]
nom = "4.0.0-beta3"
serde = "^1.0"
serde_json = "^1.0"
wasm-bindgen = { version = "^0.2", optional = true }
wee_alloc = { version = "^0.2", optional = true }