[package]
name = "gutenberg_post_parser"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]
license = "BSD-3-Clause"
readme = "./README.md"
repository = "https://github.com/Hywan/gutenberg-parser-rs"

[lib]
name = "gutenberg_post_parser"
crate-type = ["lib", "cdylib"]
path = "src/lib.rs"

[profile.release]
debug = false
lto = true
opt-level = 3

[features]
wasm = ["wee_alloc"]
default = []

[dependencies]
nom = { version = "4.0.0-beta3", default-features = false, features = ["alloc"] }
wee_alloc = { git = "https://github.com/rustwasm/wee_alloc/", branch = "master", optional = true }